"""
zoo_tycoon_builder - Generate a full playable Zoo Tycoon Python game.
Category: game_systems
Returns: success, game_dir, modules_written, systems, elapsed_ms
"""
import json
import time
from pathlib import Path
from typing import Dict, Tuple

MODULES = {
    "game_state.py": [
        "from dataclasses import dataclass, field",
        "",
        "@dataclass",
        "class Animal:",
        "    species: str",
        "    biome: str",
        "    health: float = 100.0",
        "    upkeep: float = 500.0",
        "    keeper: str = 'trained'",
        "",
        "@dataclass",
        "class ZooState:",
        "    cash: float = 50000.0",
        "    day: int = 1",
        "    prestige: int = 0",
        "    animals: list = field(default_factory=list)",
        "    reviews: list = field(default_factory=list)",
    ],
    "ticket_system.py": [
        "import random",
        "",
        "def set_base_price(rng):",
        "    return round(rng.uniform(10.0, 22.0), 2)",
        "",
        "def surge(price, occ):",
        "    m = 1.5 if occ >= 100 else 1.25 if occ >= 85 else 1.1 if occ >= 70 else 1.0",
        "    return round(price * m, 2)",
        "",
        "def child_price(adult):",
        "    return round(adult * 0.5, 2)",
    ],
    "visitor_system.py": [
        "import random",
        "",
        "def daily_visitors(rng, weekend=False):",
        "    base = 220 if weekend else 160",
        "    return max(20, round(rng.gauss(base, 45)))",
    ],
    "animal_system.py": [
        "import random",
        "",
        "CATALOGUE = [",
        "    ('lion', 'savanna', 18000, 850),",
        "    ('elephant', 'savanna', 22000, 1200),",
        "    ('penguin', 'arctic', 3000, 350),",
        "    ('gorilla', 'rainforest', 20000, 1100),",
        "    ('giraffe', 'savanna', 4000, 400),",
        "    ('tiger', 'rainforest', 21000, 1000),",
        "]",
        "",
        "def select_species(rng):",
        "    return rng.choice(CATALOGUE)",
        "",
        "def health_tick(health, keeper='trained'):",
        "    decay = {'novice': 3.5, 'trained': 1.5, 'expert': 0.5}.get(keeper, 1.5)",
        "    return round(max(0.0, health - decay), 1)",
        "",
        "def behavior(health):",
        "    if health >= 80: return 'playing'",
        "    if health >= 60: return 'active'",
        "    if health >= 40: return 'resting'",
        "    return 'lethargic'",
    ],
    "food_system.py": [
        "def food_revenue(stall_count, visitors=200):",
        "    conv = min(0.65, visitors / 500)",
        "    return round(stall_count * conv * 420.0, 2)",
        "",
        "def queue_len(visitors, stalls):",
        "    return max(0, round((visitors / max(stalls, 1)) * 0.3 - 10))",
    ],
    "staff_system.py": [
        "ROLES = {'zookeeper': 2400, 'vet': 4200, 'janitor': 1800, 'guide': 2200}",
        "",
        "def morale_tick(morale, workload='normal'):",
        "    decay = {'light': 1, 'normal': 2, 'heavy': 5, 'extreme': 10}.get(workload, 2)",
        "    return max(0, morale - decay)",
        "",
        "def get_salary(role):",
        "    return ROLES.get(role, 2000)",
    ],
    "finance_system.py": [
        "def ticket_rev(visitors, price):",
        "    return round(visitors * price, 2)",
        "",
        "def daily_expense(animals, extra=200.0):",
        "    return round(sum(a.upkeep / 30 for a in animals) + extra, 2)",
        "",
        "def pnl(rev, exp):",
        "    return round(rev - exp, 2)",
    ],
    "event_system.py": [
        "import random",
        "",
        "POSITIVE = [('viral_post', 1.3, 0), ('celebrity_visit', 1.5, 0), ('baby_born', 1.6, 0)]",
        "NEGATIVE = [('escape', 0.8, 8000), ('storm', 0.9, 5000), ('strike', 0.7, 2000)]",
        "",
        "def season(day):",
        "    return ['spring', 'summer', 'autumn', 'winter'][((day - 1) // 91) % 4]",
        "",
        "def roll_event(rng):",
        "    r = rng.random()",
        "    if r < 0.08:",
        "        name, boost, cost = rng.choice(POSITIVE)",
        "        return {'name': name, 'boost': boost, 'cost': cost}",
        "    if r < 0.15:",
        "        name, pen, cost = rng.choice(NEGATIVE)",
        "        return {'name': name, 'boost': pen, 'cost': cost}",
        "    return None",
    ],
    "reputation_system.py": [
        "def zoo_rating(visitors, cash):",
        "    vis_score = min(visitors, 500) / 100",
        "    cash_score = min(cash, 100000) / 25000",
        "    return max(1, min(5, round(vis_score + cash_score)))",
        "",
        "def aggregate(scores):",
        "    if not scores:",
        "        return {'avg': 5.0, 'total': 0}",
        "    return {'avg': round(sum(scores) / len(scores), 2), 'total': len(scores)}",
    ],
    "progression_system.py": [
        "UNLOCKS = [('petting_zoo', 100), ('aquarium_wing', 250), ('night_safari', 400), ('vip_ride', 600)]",
        "",
        "def calc_prestige(stars):",
        "    return stars * 10",
        "",
        "def unlock_check(feature, pts):",
        "    req = dict(UNLOCKS).get(feature, 9999)",
        "    return {'unlocked': pts >= req, 'required': req, 'gap': max(0, req - pts)}",
    ],
    "main.py": [
        "import random",
        "from game_state import Animal, ZooState",
        "from ticket_system import set_base_price, surge, child_price",
        "from visitor_system import daily_visitors",
        "from animal_system import health_tick, behavior, CATALOGUE",
        "from food_system import food_revenue",
        "from staff_system import get_salary",
        "from finance_system import ticket_rev, daily_expense, pnl",
        "from event_system import roll_event, season",
        "from reputation_system import zoo_rating, aggregate",
        "from progression_system import calc_prestige, unlock_check, UNLOCKS",
        "",
        "RNG = random.Random(42)",
        "",
        "",
        "def sep(title='', w=62):",
        "    if title:",
        "        p = (w - len(title) - 2) // 2",
        "        print('=' * p + ' ' + title + ' ' + '=' * (w - p - len(title) - 2))",
        "    else:",
        "        print('=' * w)",
        "",
        "",
        "def setup(state):",
        "    for name, biome, cost, upkeep in CATALOGUE[:3]:",
        "        state.animals.append(Animal(species=name, biome=biome, upkeep=upkeep))",
        "    state.cash -= 25000",
        "    sep('SETUP')",
        "    print('  Animals: ' + str([a.species for a in state.animals]))",
        "    print('  Starting cash: $' + f'{state.cash:,.0f}')",
        "    sep()",
        "",
        "",
        "def simulate_day(state, d):",
        "    wknd = d % 7 in (6, 0)",
        "    visitors = daily_visitors(RNG, wknd)",
        "    price = surge(set_base_price(RNG), RNG.randint(60, 110))",
        "    t_rev = ticket_rev(visitors, price)",
        "    f_rev = food_revenue(3, visitors)",
        "    exp = daily_expense(state.animals)",
        "    ev = roll_event(RNG)",
        "    ev_cost = 0",
        "    ev_str = ''",
        "    if ev:",
        "        ev_cost = ev.get('cost', 0)",
        "        state.cash -= ev_cost",
        "        ev_str = ' [' + ev['name'] + ' $' + str(ev_cost) + ']'",
        "        visitors = round(visitors * ev.get('boost', 1.0))",
        "    net = pnl(t_rev + f_rev, exp + ev_cost)",
        "    state.cash += pnl(t_rev + f_rev, exp)",
        "    for a in state.animals:",
        "        a.health = health_tick(a.health, a.keeper)",
        "    snr = zoo_rating(visitors, state.cash)",
        "    pts = calc_prestige(snr)",
        "    state.prestige += pts",
        "    state.reviews.append(snr)",
        "    szn = season(d)",
        "    wknd_flag = '*' if wknd else ' '",
        "    rev_total = t_rev + f_rev",
        "    tag = f'Day {d:2d} [{szn:6s}{wknd_flag}]'",
        "    print(f'{tag}: {visitors:3d}vis  rev=${rev_total:,.0f}  exp=${exp:,.0f}  net=${net:+,.0f}  cash=${state.cash:,.0f}  stars={snr}{ev_str}')",
        "",
        "",
        "def main():",
        "    sep('ZOO TYCOON')",
        "    print('  Text-based zoo management simulation')",
        "    sep()",
        "    state = ZooState()",
        "    setup(state)",
        "    print('Simulating 10 days...')",
        "    print()",
        "    for d in range(1, 11):",
        "        simulate_day(state, d)",
        "    print()",
        "    sep('FINAL REPORT')",
        "    agg = aggregate(state.reviews)",
        "    cash_str = f'{state.cash:,.2f}'",
        "    print('  Zoo cash   : $' + cash_str)",
        "    print('  Prestige   : ' + str(state.prestige))",
        "    print('  Animals    : ' + str(len(state.animals)))",
        "    avg_str = str(agg['avg'])",
        "    print('  Avg rating : ' + avg_str + '/5 stars')",
        "    for feat, _ in UNLOCKS:",
        "        u = unlock_check(feat, state.prestige)",
        "        if u['unlocked']:",
        "            print('  UNLOCKED   : ' + feat)",
        "    sep()",
        "",
        "",
        "if __name__ == '__main__':",
        "    main()",
    ],
    "README.md": [
        "# Zoo Tycoon",
        "",
        "Generated by `zoo_tycoon_builder`.",
        "",
        "## Run",
        "```",
        "cd zoo_tycoon_game",
        "python main.py",
        "```",
        "",
        "## Systems",
        "- ticket_system, visitor_system, animal_system",
        "- food_system, staff_system, finance_system",
        "- event_system, reputation_system, progression_system",
        "- game_state, main",
    ],
}


def run_zoo_tycoon_builder(repo_path: str):
    t0 = time.monotonic()
    game_dir = Path(repo_path).resolve() / 'zoo_tycoon_game'
    game_dir.mkdir(parents=True, exist_ok=True)
    written = []
    systems = []
    for fname, file_lines in MODULES.items():
        (game_dir / fname).write_text('\n'.join(file_lines), encoding='utf-8')
        written.append(fname)
        if 'system' in fname:
            systems.append(fname.replace('.py', ''))
    elapsed = round((time.monotonic() - t0) * 1000)
    rel = str(game_dir.relative_to(Path(repo_path).resolve())).replace('\\', '/')
    return 0, {
        'success': True,
        'game_dir': rel,
        'modules_written': len(written),
        'files': written,
        'systems': systems,
        'elapsed_ms': elapsed,
        'summary': f'Zoo Tycoon: {len(written)} files in zoo_tycoon_game/. Run: python zoo_tycoon_game/main.py',
    }


def cmd_zoo_tycoon_builder(repo_path: str):
    code, payload = run_zoo_tycoon_builder(repo_path)
    import json as _json; print(_json.dumps(payload))
    return code, payload