#!/usr/bin/env python3
"""Generated by game_v2_pipeline_orchestrator using small builders."""
import argparse
from core.theme import describe_theme
from systems.encounter import roll_encounter, resolve_encounter
from systems.narrative import scene_line
from systems.player import create_player, rest_player
from systems.progression import apply_rewards

def _print_header(theme):
    print(f"=== {theme['title']} ===")
    print(f"Archetype: {theme['archetype']} | Relic: {theme['relic']} | Faction: {theme['faction']}")
    print(f"Seed: {theme['seed']}")

def preview_turn(theme):
    player = create_player()
    encounter = roll_encounter('medium')
    outcome = resolve_encounter(player, encounter)
    apply_rewards(player, outcome)
    print(scene_line(theme, 0))
    print(f"Encounter: {encounter['name']} ({encounter['threat']})")
    print(f"Outcome: {'victory' if outcome['won'] else 'retreat'}")
    print(f"Level {player['level']} | HP {player['hp']} | XP {player['xp']} | Gold {player['gold']}")

def play_loop(theme):
    player = create_player()
    turn = 0
    print("Interactive mode: scout, rest, status, quit")
    while True:
        cmd = input('> ').strip().lower()
        if cmd in {'quit', 'q', 'exit'}:
            print('You leave the frontier for now.')
            return
        if cmd in {'status', 's'}:
            print(f"Level {player['level']} | HP {player['hp']} | XP {player['xp']} | Gold {player['gold']}")
            continue
        if cmd in {'rest', 'r'}:
            rest_player(player)
            print('You rest and recover composure.')
            continue
        if cmd not in {'scout', 'explore', 'e'}:
            print('Unknown command. Try: scout, rest, status, quit')
            continue

        encounter = roll_encounter('high' if turn > 1 else 'medium')
        outcome = resolve_encounter(player, encounter)
        apply_rewards(player, outcome)
        print(scene_line(theme, turn))
        print(f"Encounter: {encounter['name']} ({encounter['threat']})")
        print(f"Outcome: {'victory' if outcome['won'] else 'hard-fought retreat'}")
        print(f"Level {player['level']} | HP {player['hp']} | XP {player['xp']} | Gold {player['gold']}")
        turn += 1

def main(argv=None):
    parser = argparse.ArgumentParser(description='Generated adventure game')
    parser.add_argument('--play', action='store_true', help='Run interactive loop')
    args = parser.parse_args(argv)

    theme = describe_theme()
    _print_header(theme)
    preview_turn(theme)
    if args.play:
        play_loop(theme)

if __name__ == '__main__':
    main()
