"""add_gameplay_features

Revision ID: 03cdcf4e5749
Revises: 21aad8756577
Create Date: 2026-02-07 18:29:52.064327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03cdcf4e5749'
down_revision: Union[str, None] = '21aad8756577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest_events') as batch_op:
        batch_op.alter_column(
            'streak_multiplier',
            existing_type=sa.INTEGER(),
            type_=sa.Float(),
            existing_nullable=True,
        )
    op.add_column('users', sa.Column('resilience_tokens', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_perfect_day', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_perfect_day')
    op.drop_column('users', 'resilience_tokens')
    with op.batch_alter_table('quest_events') as batch_op:
        batch_op.alter_column(
            'streak_multiplier',
            existing_type=sa.Float(),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
    # ### end Alembic commands ###
